### ISSUE TITLE
Australia.osm.pbf data

### ISSUE THREAD

**Issue by ns-1m** [andrewharvey/osm-hybrid-carto#1]
Hi Andrew,

I am trying to use Australia.osm.pbf from geofabrik and import to my PostGIS using Osm2pgsql. 

http://download.geofabrik.de/osm/australia-oceania/

I was not be to view the polygons in TileMill. The postgis supplying the data in Tilemill as I can see it in the view data in various layers but no display any map (i.e. layers).

I got these errors (below) in the various layers.

I am very interested to get Victoria OSM data with your  osm-hybrid-carto theme in TileMill.

Do you know any idea why? I am using Mac OS X and TileMill 0.5.1.

Thanks in advance
###### 

Error: : ERROR: column "tags" does not exist LINE 9: tags->'cycleway' as cycleway ^ Full sql was: 'SELECT \* FROM ( SELECT way, highway, access, bridge, tunnel, name, tags->'cycleway' as cycleway FROM planet_osm_line WHERE highway in ('cycleway') ) AS cycleway LIMIT 0'

Error: : ERROR: column "tags" does not exist LINE 7: tags->'cuisine' as cuisine, ^ Full sql was: 'SELECT \* FROM ( ( SELECT way, amenity, shop, tags->'cuisine' as cuisine, name FROM planet_osm_point WHERE ( shop IS NOT null OR amenity IN ('fast_food') ) ) UNION ( SELECT ST_Centroid(way) as way, amenity, shop, tags->'cuisine' as cuisine, name FROM planet_osm_line WHERE ( shop IS NOT null OR amenity IN ('fast_food') ) ) ) AS shoppoi LIMIT 0'

Error: : ERROR: column "tags" does not exist LINE 11: tags->'school:level' as school_level, ^ Full sql was: 'SELECT \* FROM ( ( SELECT way, amenity, man_made, tourism, leisure, barrier, building, tags->'school:level' as school_level, name FROM planet_osm_point WHERE (amenity IS NOT null OR man_made IS NOT null OR tourism IS NOT null OR leisure IS NOT null OR barrier IS NOT null OR building IS NOT null) ) UNION ( SELECT ST_Centroid(way) as way, amenity, man_made, tourism, leisure, barrier, null, tags->'school:level' as school_level, name FROM planet_osm_line WHERE (amenity IS NOT null OR man_made IS NOT null OR tourism IS NOT null OR leisure IS NOT null OR barrier IS NOT null) ) ) AS amenity_poi LIMIT 0'

Error: : ERROR: column "tags" does not exist LINE 9: tags->'footway' as footway, ^ Full sql was: 'SELECT \* FROM ( SELECT way, highway, access, bridge, tunnel, name, tags->'footway' as footway, tags->'sidewalk' as sidewalk FROM planet_osm_line WHERE highway in ('footway', 'steps') ) AS highway LIMIT 0'

**Comment by andrewharvey** [comment]
Hi Noli,

I'm glad to see you trying out this style sheet for yourself. The error about "tags" is because you need to import the OSM data using osm2pgsql with the --hstore option. I believe this is all you need, I don't think I've made any changes to the import style, a recent http://svn.openstreetmap.org/applications/utils/export/osm2pgsql/default.style should work. Let me know if it doesn't.

**Comment by ns-1m** [comment]
Hi Andrew,

Thanks for replying.

What sort of options do I need to put in --hstore?

I tried this:

osm2pgsql -d osm --hstore australia.osm.pbf

I did not work, see the error below.

Thanks again. Noli

############
localhost:work1 noli$ osm2pgsql -d osm --hstore australia.osm.pbf
osm2pgsql SVN version 0.70.5 (32bit id space)

Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point" does not exist, skipping
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
CREATE TABLE planet_osm_point ( osm_id int4,"access"
text,"addr:housename" text,"addr:housenumber"
text,"addr:interpolation" text,"admin_level" text,"aerialway"
text,"aeroway" text,"amenity" text,"area" text,"barrier"
text,"bicycle" text,"brand" text,"bridge" text,"boundary"
text,"building" text,"capital" text,"construction" text,"covered"
text,"culvert" text,"cutting" text,"denomination" text,"disused"
text,"ele" text,"embankment" text,"foot" text,"generator:source"
text,"harbour" text,"highway" text,"historic" text,"horse"
text,"intermittent" text,"junction" text,"landuse" text,"layer"
text,"leisure" text,"lock" text,"man_made" text,"military"
text,"motorcar" text,"name" text,"natural" text,"oneway"
text,"operator" text,"poi" text,"population" text,"power"
text,"power_source" text,"place" text,"railway" text,"ref"
text,"religion" text,"route" text,"service" text,"shop" text,"sport"
text,"surface" text,"toll" text,"tourism" text,"tower:type"
text,"tunnel" text,"water" text,"waterway" text,"wetland" text,"width"
text,"wood" text,"z_order" int4,tags hstore)
 failed: ERROR:  type "hstore" does not exist
LINE 1: ...d" text,"width" text,"wood" text,"z_order" int4,tags hstore)

On 10/10/11, Andrew Harvey
reply@reply.github.com
wrote:

**Comment by andrewharvey** [comment]
See http://wiki.openstreetmap.org/wiki/Osm2pgsql#hstore

You need to load the hstore extension for your psql database with something along the lines of `psql -d osm -f /usr/share/postgresql/8.4/contrib/hstore.sql` depending on your postgresql version.

**Comment by andrewharvey** [comment]
Also... if you want to be able to see the POI symbols you will need the SJJB icons http://www.sjjb.co.uk/mapicons/downloads. My style sheet has these paths hard coded as /usr/share/icons/sjjb/png/... You will either need to change this or install the icons there.

**Comment by ns-1m** [comment]
It seems that postgresql 9.x does not have yet hstore module. I am
using 9.1 and PostGIS 1.5.

http://stackoverflow.com/questions/4776563/how-do-i-install-the-hstore-module-on-postgresql-9-0-macports-install

Thanks again for your help.

On 10/10/11, Andrew Harvey
reply@reply.github.com
wrote:

**Comment by andrewharvey** [comment]
You could edit the stylesheet to never use the tags hstore.. either dropping them, or adding the tags I access through it as column by editing your osm2pgsql style file.

**Comment by ns-1m** [comment]
I have not solved anything regarding hstore. I still got errors in
TileMill on those queries.  Although, I can see the testhstore table
created in my osm database using pgAdmin3.

Right now, I am figuring to get the mapnik compiling in Mac OS X. The
greatest problem is fontconfig which is needed for cairo. Cairo is
need for mapnik.  Fontconfig is not compiling.

I think it is easier to do the mapnik, osm2pgsql and TileMill in Ubuntu.

Andrew, what version of Ubuntu are you using?

Dane the author of Mapnik and TileMill is also helping me to compiling
mapnik for Mac OS X.

On 10/12/11, Andrew Harvey
reply@reply.github.com
wrote:

**Comment by andrewharvey** [comment]
There are mapnik2, osm2pgsql, postgres and postgis (with hstore) packages for Ubuntu so that should ease the set up.

My set up is more complicated. I'm using Debian for my database, and running TileMill inside an Ubuntu virtual machine (using the TileMill and Mapnik2 PPAs). Any of the two latest Ubuntu releases should be fine.

For my live demo I run Debian with mapnik2 from unstable, where I use the xml export from TileMill with TileStache as my tileserver proxied through lighttpd. In the long term I would like to see a mod_tile for lighttpd and combine that with tirex as my tileserver. One step at a time though.

**Comment by ns-1m** [comment]
Hi Andrew,

I managed to run TileMill in Ubuntu 10.04 and compiled from source.

https://github.com/mapbox/tilemill/issues/789

However, I still don't get the geometry column (i.e. way) to render in
the map canvas.

Any pointers what to check in the PostGIS to make osmt working?

Thanks. Noli

On 10/12/11, Andrew Harvey
reply@reply.github.com
wrote:
