### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by valerio-bozzolan** [andrewharvey/osm-hybrid-carto#4]
I noticed that the demo in the README does not work :)

http://tianjara.net/leaflet.html#map=agri,osmt;lat=-33.89;lon=151.27;zoom=15

**Comment by andrewharvey** [comment]
Yeah I don't maintain this or the demo anymore, this was a 10 year old experiment.

**Comment by valerio-bozzolan** [comment]
Ouch :(

Thank you anyway!
